version: '2'
services:
  db:
    image: oracle/database:12.2.0.1-ee
    container_name: oracle
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./oradata:/opt/oracle/oradata
    environment:
      - ORACLE_PWD=Oracle12
      - ORACLE_PDB=oracle

